// <auto-generated />
using System;
using Cleiteam.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cleiteam.API.Migrations
{
    [DbContext(typeof(CleiteamContext))]
    [Migration("20231005220621_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cleiteam.Domain.Entities.ComentarioImagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdImagem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdImagem");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ComentariosImagem");
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.ImagemOcorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdOcorrencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdOcorrencia");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ImagensOcorrencia", (string)null);
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.Ocorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("IdSubtipoOcorrencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("Decimal(8,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("Decimal(9,6)");

                    b.HasKey("Id");

                    b.HasIndex("IdSubtipoOcorrencia");

                    b.ToTable("Ocorrencias", (string)null);
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.SubtipoOcorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("IdTipoOcorrencia")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoOcorrencia");

                    b.ToTable("SubtiposOcorrencia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4e12ea1-3f8b-4caa-ad22-42aebc37a497"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5539),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5540),
                            Descricao = "Postes de luz danificados",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("0a2615af-e5b8-45e4-9216-afe540aa2080"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5543),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5544),
                            Descricao = "Lâmpadas de rua queimadas ou piscando",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("c83d5e61-33ba-4007-8260-bcee4169c9e9"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5548),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5549),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("4914af6f-0274-44db-a383-eb5d25dbc613"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5551),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5551),
                            Descricao = "Buracos nas estradas",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea1")
                        },
                        new
                        {
                            Id = new Guid("7490eaca-d535-400f-a009-a5ec6f50278f"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5554),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5554),
                            Descricao = "Sinalização inadequada ou ausente",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea1")
                        },
                        new
                        {
                            Id = new Guid("d1883cf6-34d4-4603-8887-4de4b406e9a3"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5556),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5557),
                            Descricao = "Problemas de congestionamento de tráfego",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea1")
                        },
                        new
                        {
                            Id = new Guid("70063257-58b7-4c8a-aecf-77b7993cb9f9"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5561),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5561),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea1")
                        },
                        new
                        {
                            Id = new Guid("9539eb44-58e7-4859-a473-ccc697dfb936"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5563),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5563),
                            Descricao = "Atrasos ou interrupções nos serviços de transporte público",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea2")
                        },
                        new
                        {
                            Id = new Guid("39fc1183-0f69-4ae5-adb4-acdcba4fe475"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5566),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5566),
                            Descricao = "Veículos sujos ou danificados",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea2")
                        },
                        new
                        {
                            Id = new Guid("2ca9d8fa-67f1-4fd1-a06c-173dbf94112a"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5568),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5569),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea2")
                        },
                        new
                        {
                            Id = new Guid("8639e4d9-f83a-4720-b5ae-f74f44becdcb"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5572),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5573),
                            Descricao = "Coleta irregular de lixo",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea3")
                        },
                        new
                        {
                            Id = new Guid("29c51f6a-3363-491b-9858-3fa5c5b40034"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5575),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5575),
                            Descricao = "Recipientes de reciclagem danificados",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea3")
                        },
                        new
                        {
                            Id = new Guid("9dbc7775-30a4-4617-a819-2dd83b617352"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5578),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5578),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea3")
                        },
                        new
                        {
                            Id = new Guid("bafa9694-3040-461f-9182-48313619f535"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5580),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5581),
                            Descricao = "Postes de luz danificados",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea4")
                        },
                        new
                        {
                            Id = new Guid("fbdac80a-c37b-4731-91f7-86e5eca7a73f"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5584),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5585),
                            Descricao = "Lampadas de rua queimadas ou piscando",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea4")
                        },
                        new
                        {
                            Id = new Guid("f50800e7-6d70-4b5b-82b0-831a16ea5786"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5587),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5587),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea4")
                        },
                        new
                        {
                            Id = new Guid("ded0d718-fc97-4c37-bff1-c4740e783fe5"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5590),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5590),
                            Descricao = "Vazamentos de água visíveis",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea5")
                        },
                        new
                        {
                            Id = new Guid("e5649d5a-6031-41aa-82e5-e2793dbaa32c"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5592),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5593),
                            Descricao = "Problemas com o abastecimento de água potável",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea5")
                        },
                        new
                        {
                            Id = new Guid("34460679-2f95-49fd-bb28-274416265c4a"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5597),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5597),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea5")
                        },
                        new
                        {
                            Id = new Guid("aa8e02e3-9058-4882-ad4b-0ee77dc6fa2c"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5599),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5600),
                            Descricao = "Problemas com esgoto ou drenagem",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea6")
                        },
                        new
                        {
                            Id = new Guid("248899f6-faae-47ca-83c7-91c53174cff1"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5602),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5602),
                            Descricao = "Entupimentos ou refluxo de esgoto",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea6")
                        },
                        new
                        {
                            Id = new Guid("43c5c10a-5239-4a0a-8052-413717ada3b6"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5604),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5605),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea6")
                        },
                        new
                        {
                            Id = new Guid("1db69d2b-d644-45bf-b169-1e3ef30ce669"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5609),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5609),
                            Descricao = "Iluminação Pública",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea7")
                        },
                        new
                        {
                            Id = new Guid("8a5ee411-cc9d-4378-ac63-f62cf98f8c19"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5611),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5612),
                            Descricao = "Postes de luz danificados",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea7")
                        },
                        new
                        {
                            Id = new Guid("aca339be-bdc7-4d97-8dfc-043656a87e93"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5614),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5614),
                            Descricao = "Lâmpadas de rua queimadas ou piscando",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea7")
                        },
                        new
                        {
                            Id = new Guid("bfcd1553-3de2-43ef-af73-ddf959c174b7"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5616),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5617),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea7")
                        },
                        new
                        {
                            Id = new Guid("0b3747d3-b3af-4d7c-aeb0-3903dbfed9fa"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5621),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5621),
                            Descricao = "Problemas nos hospitais públicos ou clínicas de saúde",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea8")
                        },
                        new
                        {
                            Id = new Guid("45d7330a-8fd7-469e-8cd8-c69a3b58e511"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5623),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5623),
                            Descricao = "Falhas na distribuição de vacinas ou medicamentos",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea8")
                        },
                        new
                        {
                            Id = new Guid("c180b287-273d-4117-b704-d66591932017"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5626),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5626),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea8")
                        },
                        new
                        {
                            Id = new Guid("b876255c-72d5-4db3-b45f-492423d4a00b"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5628),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5629),
                            Descricao = "Problemas com abrigos ou programas de assistência a pessoas em situação de rua",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea9")
                        },
                        new
                        {
                            Id = new Guid("6fd22df9-f109-4b92-bb0e-f852b851203b"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5632),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5633),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea9")
                        },
                        new
                        {
                            Id = new Guid("534cf056-bffb-4075-a9d1-d0595355b488"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5635),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5635),
                            Descricao = "Dificuldades para entrar em contato com os órgãos governamentais",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4218-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("77847aaa-ca33-400d-b8af-8168e7e75ed9"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5638),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5638),
                            Descricao = "Respostas lentas a reclamações ou pedidos de assistência",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4218-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("72068216-3282-4987-920b-0548a19f0b60"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5640),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5640),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4218-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("b963c996-012c-47b6-b981-7d0d9699919d"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5644),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5645),
                            Descricao = "Poluição do ar ou da água",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4228-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("299edddf-c040-42c4-a2a5-c220285ec77f"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5647),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5647),
                            Descricao = "Descarte inadequado de resíduos",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4228-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("d4c19a09-4d9c-40eb-a8dd-6c4d7b760081"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5649),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5650),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4228-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("9265cb6b-99e4-4cde-a0b0-71da22826c6a"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5652),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5652),
                            Descricao = "Zonas perigosas ou locais com alto índice de criminalidade",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4238-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("78c4fbb9-87e7-41d1-af0c-7a9a0a77088b"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5656),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5656),
                            Descricao = "Necessidade de melhorias na iluminação de áreas públicas para a segurança dos cidadãos",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4228-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("d15ee95e-3219-48f7-bbea-1f6363cc8fca"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5659),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5659),
                            Descricao = "Ruído excessivo",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4248-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("25fd807c-3c13-4a57-a3e1-87a34b439c3f"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5661),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5661),
                            Descricao = "Falta de estacionamento público",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4248-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("04519d3e-d29f-420c-ba09-fd9f286d0019"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5664),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5664),
                            Descricao = "Problemas com transporte de animais de estimação ou controle de pragas",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4248-9abb-792c2b979ea0")
                        },
                        new
                        {
                            Id = new Guid("d32a6fb7-1342-40f4-bb3a-68684e3276ee"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5668),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5668),
                            Descricao = "Outros",
                            IdTipoOcorrencia = new Guid("b8e6cd20-4268-4248-9abb-792c2b979ea0")
                        });
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.TipoOcorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposOcorrencia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea0"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5323),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5323),
                            Descricao = "Iluminação Pública"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea1"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5327),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5327),
                            Descricao = "Estradas e Tráfego"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea2"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5329),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5330),
                            Descricao = "Transporte Público"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea3"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5371),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5371),
                            Descricao = "Coleta de Lixo e Reciclagem"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea4"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5374),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5374),
                            Descricao = "Manutenção de Parques e Praças"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea5"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5376),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5376),
                            Descricao = "Abastecimento de Água"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea6"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5378),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5379),
                            Descricao = "Saneamento Básica"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea7"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5381),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5381),
                            Descricao = "Serviços de Emergência"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea8"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5383),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5383),
                            Descricao = "Serviços de Saúde"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4208-9abb-792c2b979ea9"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5385),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5385),
                            Descricao = "Assistência Social"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4218-9abb-792c2b979ea0"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5387),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5387),
                            Descricao = "Atendimento ao Cliente"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4228-9abb-792c2b979ea0"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5393),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5393),
                            Descricao = "Questões Ambientais"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4238-9abb-792c2b979ea0"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5395),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5395),
                            Descricao = "Problemas de Segurança"
                        },
                        new
                        {
                            Id = new Guid("b8e6cd20-4268-4248-9abb-792c2b979ea0"),
                            DataCriacao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5397),
                            DataEdicao = new DateTime(2023, 10, 5, 19, 6, 21, 712, DateTimeKind.Local).AddTicks(5397),
                            Descricao = "Outras Preocupações Cidadãs"
                        });
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.UsuarioConfiguracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Alcance")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("ReceberNotificacao")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UsuarioConfiguracoes", (string)null);
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.UsuarioOcorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEdicao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdOcorrencia")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Responsavel")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdOcorrencia");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuarioOcorrencias", (string)null);
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.ComentarioImagem", b =>
                {
                    b.HasOne("Cleiteam.Domain.Entities.ImagemOcorrencia", "Imagem")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdImagem")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cleiteam.Domain.Entities.UsuarioConfiguracao", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imagem");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.ImagemOcorrencia", b =>
                {
                    b.HasOne("Cleiteam.Domain.Entities.Ocorrencia", "Ocorrencia")
                        .WithMany("Imagens")
                        .HasForeignKey("IdOcorrencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cleiteam.Domain.Entities.UsuarioConfiguracao", "Usuario")
                        .WithMany("Imagens")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.Ocorrencia", b =>
                {
                    b.HasOne("Cleiteam.Domain.Entities.SubtipoOcorrencia", "SubtipoOcorrencia")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("IdSubtipoOcorrencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubtipoOcorrencia");
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.SubtipoOcorrencia", b =>
                {
                    b.HasOne("Cleiteam.Domain.Entities.TipoOcorrencia", "TipoOcorrencia")
                        .WithMany("SubtiposOcorrencia")
                        .HasForeignKey("IdTipoOcorrencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoOcorrencia");
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.UsuarioOcorrencia", b =>
                {
                    b.HasOne("Cleiteam.Domain.Entities.Ocorrencia", "Ocorrencia")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdOcorrencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cleiteam.Domain.Entities.UsuarioConfiguracao", "Usuario")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.ImagemOcorrencia", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.Ocorrencia", b =>
                {
                    b.Navigation("Imagens");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.SubtipoOcorrencia", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.TipoOcorrencia", b =>
                {
                    b.Navigation("SubtiposOcorrencia");
                });

            modelBuilder.Entity("Cleiteam.Domain.Entities.UsuarioConfiguracao", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Imagens");

                    b.Navigation("Ocorrencias");
                });
#pragma warning restore 612, 618
        }
    }
}
